=== mbekele0503/Group_D/src/main/resources/api/Examples/noteinsertschema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "createDate": {
      "type": "string"
    },
    "updateDate": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "title",
    "content",
    "createDate",
    "updateDate"
  ]
}

=== mbekele0503/Group_D/src/main/resources/api/Examples/noteEX.json
[
                {
                  "id": 101,
                  "title": "VP Reporting",
                  "content": "salls has been reported",
                  "createDate": "2015-07-04T21:00:00", 
                  "updateDate": "2015-07-04T21:00:00"
                },
                {
                  "id": 102,
                  "title": "CFO Reporting",
                  "content": "4th quarter report",
                  "createDate": "2015-07-04T21:00:00",
                  "updateDate": "2015-07-04T21:00:00"
                }
]
